#!/bin/bash



export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g -fno-pie'
export CXXFLAGS='-g -fno-pie'
export LDFLAGS='-g -fno-pie'

./configure.sh

make
