#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
    ./configure --help
    exit 1
fi

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g -fno-pie -O3'
export CXXFLAGS='-g -fno-pie -O3'
export LDFLAGS='-g -fno-pie -O3'
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

if [[ ! -e ./configure ]]; then
    ./autogen.sh
fi

./configure --with-template=linux --without-readline --without-zlib USE_DEV_URANDOM=1 --host=x86_64-nacl "$@"

make
