dir .
dir ../../gcc-4.4.3/gcc
dir ../../gcc-4.4.3/gcc/ada
dir ../../gcc-4.4.3/gcc/cp
dir ../../gcc-4.4.3/gcc/fortran
dir ../../gcc-4.4.3/gcc/java
dir ../../gcc-4.4.3/gcc/objc
dir ../../gcc-4.4.3/gcc/objcp
source ../../gcc-4.4.3/gcc/gdbinit.in
