#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
	make help
	exit 1
fi

defines="-D__KERNEL_STRICT_NAMES"
defines="$defines -D__kernel_long_t=int64_t"
defines="$defines -D__kernel_ulong_t=uint64_t"
prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}"

export CROSS_COMPILE=x86_64-nacl-
export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS="-g3 -fPIC $defines"
export CXXFLAGS="-g3 -fPIC $defines"
export LDFLAGS="-g3 -fPIC $defines"
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

mkdir -pv "$prefix"
cp -v ./busybox.config ./.config
make menuconfig
sed -i "s!.*CONFIG_PREFIX.*!CONFIG_PREFIX=\"$prefix\"!" .config

make && make install
