.TH lind: "1" "June 2017" "lind: lind v0.0.1" "User Commands"

.SH "NAME"
lind - lind

.SH "SYNOPSIS"
.sp
.nf
\fIlind\fR [\-hv] [\-o\fI<output.c>\fR]
.fi

.SH "DESCRIPTION"
.sp

.SH "USAGE"
.sp
lind

.SS "COMMANDS"
.sp
lind

.SS "OPTIONS"
.sp
Command line options:

.HP
\fB\-h\fR,\fB\-\-help\fR:	Show help/usage information.
.HP
\fB\-v\fR,\fB\-\-version\fR:	Show version information.
.HP
\fB\-o\fR:			Name of the file to output source to.

.SH "AUTHORS"
.sp

.SH "NOTES"
.sp
https://github.com/Lind-Project/lind_project
