.TH <template>: "1" "June 2017" "<template>: <template> v0.0.1" "User Commands"

.SH "NAME"
<template> - <template>

.SH "SYNOPSIS"
.sp
.nf
\fI<template>\fR [\-hv] [\-o\fI<output.c>\fR]
.fi

.SH "DESCRIPTION"
.sp
<template>
general algorithm exploration.

.SH "USAGE"
.sp
<template>

.SS "COMMANDS"
.sp
<template>

.SS "OPTIONS"
.sp
Command line options:

.HP
\fB\-h\fR,\fB\-\-help\fR:	Show help/usage information.
.HP
\fB\-v\fR,\fB\-\-version\fR:	Show version information.
.HP
\fB\-o\fR:			Name of the file to output source to.

.SH "AUTHOR"
.sp
Joey Pabalinas <joeypabalinas@gmail.com>

.SH "NOTES"
.sp
https://github.com/<template>/<template>
