#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
	if [[ -f ./configure ]]; then
		./configure --help
		exit 1
	fi
	./buildconf --help
	exit 1
fi

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g -fno-pie'
export CXXFLAGS='-g -fno-pie'
export LDFLAGS='-g -fno-pie'
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

rm -fv -- ./configure
./buildconf
./configure \
	--with-included-apr \
	--with-expat=builtin \
	--enable-mods-shared=most \
	--enable-ssl \
	--enable-proxy \
	--enable-proxy-connect \
	--enable-proxy-http \
	--enable-proxy-balancer \
	--host=x86_64-nacl \
	"$@" \
	ac_cv_file__dev_zero="yes" \
	ac_cv_func_setpgrp_void="yes" \
	apr_cv_process_shared_works="yes" \
	apr_cv_mutex_robust_shared="no" \
	apr_cv_tcp_nodelay_with_cork="yes" \
	ac_cv_sizeof_struct_iovec="8" \
	apr_cv_mutex_recursive="yes"

make
