top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/modules/filters
builddir     = /home/jp/lind_project/test_cases/httpd/modules/filters
VPATH        = /home/jp/lind_project/test_cases/httpd/modules/filters

include $(top_srcdir)/build/special.mk

