top_srcdir   = /home/jp/lind_project/test_cases/httpd-2.4.37
top_builddir = /home/jp/lind_project/test_cases/httpd-2.4.37
srcdir       = /home/jp/lind_project/test_cases/httpd-2.4.37/modules
builddir     = /home/jp/lind_project/test_cases/httpd-2.4.37/modules
VPATH        = /home/jp/lind_project/test_cases/httpd-2.4.37/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

