top_srcdir   = /home/jp/lind_project/test_cases/httpd-2.4.37
top_builddir = /home/jp/lind_project/test_cases/httpd-2.4.37
srcdir       = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/generators
builddir     = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/generators
VPATH        = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/generators

include $(top_srcdir)/build/special.mk

