top_srcdir   = /home/jp/lind_project/test_cases/httpd-2.4.37
top_builddir = /home/jp/lind_project/test_cases/httpd-2.4.37
srcdir       = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/dav/main
builddir     = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/dav/main
VPATH        = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
