top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/modules/metadata
builddir     = /home/jp/lind_project/test_cases/httpd/modules/metadata
VPATH        = /home/jp/lind_project/test_cases/httpd/modules/metadata

include $(top_srcdir)/build/special.mk

