#!/bin/bash

export AR=x86_64-nacl-ar
export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g -fPIC -fpie'
export CXXFLAGS='-g -fPIC -fpie'
export LDFLAGS='-g -fPIC -fpie'
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"
export PREFIX="${PREFIX:-$HOME/lind_project/lind/repy/repy}"

./configure \
	--enable-shared \
	--host=x86_64-nacl \
	--prefix="$PREFIX" \
	"$@"

make install
