top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/server/mpm/prefork
builddir     = /home/jp/lind_project/test_cases/httpd/server/mpm/prefork
VPATH        = /home/jp/lind_project/test_cases/httpd/server/mpm/prefork
include $(top_srcdir)/build/special.mk
