#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
        if [[ ! -f ./configure ]]; then
		./autogen.sh
        fi
	./configure --help
	exit 1
fi

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-I./contrib/libev/ -g -fno-pie'
export CXXFLAGS='-I./contrib/libev/ -g -fno-pie'
export LDFLAGS='-g -fno-pie'
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"
export PREFIX="${PREFIX:-$HOME/lind_project/lind/repy/repy}"

rm -fv -- ./configure
./autogen.sh
./configure \
	--prefix="$PREFIX" \
	--sbindir="$PREFIX/bin" \
	--libdir="$PREFIX/lib/lighttpd/" \
	--sysconfdir="$PREFIX/etc/lighttpd" \
	--with-libev=./contrib/libev \
	--with-pic \
	--with-attr \
	--with-webdav-props \
	--with-webdav-locks \
	--without-kerberos5 \
	--without-mysql \
	--without-ldap \
	--without-openssl \
	--without-fam \
	--without-gdbm \
	--without-lua \
	--host=x86_64-nacl \
	"$@"

make
