top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/modules/http
builddir     = /home/jp/lind_project/test_cases/httpd/modules/http
VPATH        = /home/jp/lind_project/test_cases/httpd/modules/http

include $(top_srcdir)/build/special.mk

