top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/modules
builddir     = /home/jp/lind_project/test_cases/httpd/modules
VPATH        = /home/jp/lind_project/test_cases/httpd/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

