.TH "runcon" 1 "GNU coreutils 8.30.10-e5dae2-dirty" "User Commands"
.SH NAME
runcon \- a GNU coreutils 8.30.10-e5dae2-dirty program
.SH DESCRIPTION
.B OOPS!
We were unable to create a proper manual page for
.B runcon.
For concise option descriptions, run
.IP
.B env runcon --help
.PP
The full documentation for
.B runcon
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) runcon invocation\(aq
