#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
	if [[ -f ./configure ]]; then
		./configure --help
		exit 1
	fi
	./buildconf --help
	exit 1
fi

# clean compiler environment
unset CARCH CCACHE_DISABLE CFLAGS CCFLAGS
unset CHOST C_INCLUDE_PATH CPATH CPPFLAGS
unset CXXFLAGS LDFLAGS LIBRARY_PATH

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g3 -fPIC'
export CXXFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g3 -fPIC'
export LDFLAGS='-g3 -fPIC'
export PREFIX="${PREFIX:-$HOME/lind_project/lind/repy/repy}"
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

mkdir -pv -- apr
make clean || true
make distclean || true
rm -fv -- ./configure
for d in srclib/apr{,-util}; do
	(cd "$d" \
		&& (make clean || true) \
		&& (make distclean || true) \
		&& rm -fv -- ./configure \
		&& ./bootstrap_nacl --prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}" \
		&& make install)
done
cp -fv -- srclib/apr-util/include/{apr_{hooks,optional_hooks,buckets,uri,optional},apu}.h include/
find . -type f -name '*build-outputs.mk' -delete
./buildconf
./configure \
	--with-included-apr \
	--with-libxml2="$PREFIX/lib" \
	--with-brotli="$PREFIX" \
	--with-pcre="$PREFIX" \
	--with-z="$PREFIX" \
	--host=x86_64-nacl \
	--enable-mods-shared=most \
	--prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}" \
	--exec-prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}" \
	"$@" \
	ac_cv_file__dev_zero="yes" \
	ac_cv_func_setpgrp_void="yes" \
	apr_cv_tcp_nodelay_with_cork="yes" \
	ap_cv_void_ptr_lt_long="no" \
	ac_cv_sizeof_struct_iovec="8" \
	apr_cv_process_shared_works="yes" \
	apr_cv_mutex_robust_shared="no" \
	apr_cv_mutex_recursive="yes"

patch -Np1 <./httpd.h.patch || true

# fix multiple definition errors
if ! make; then
	cp -fv -- server/exports.c{.patched,}
	patch -Np1 <./mutex.patch || true
	make
fi
make install
