# Copyright (c) 2015 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Default user bashrc file for NaCl DevEnv.  This gets executed by bash
# for each interative shell.

# some aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'
alias ruby='ruby /bin/irb'
alias emacs='ENABLE_CONTROL_C=0 emacs'

# TODO(bradnelson): Drop this when we can install things in a more
# normal location and when we include the git templates in the normal
# location.
# Disabling templatedir as our git package lacks a default template set.
# Setting up a default git identity, since we lack /etc/passwd as
# a fallback.
# Setup default .gitconfig if it doesn't already exist.
# Explictly use [[ ]] conditional here in case coreutils is missing.
gitdirs=(/stamps/git*)
if [[ ${#dirdirs[@]} -gt 0 && ! -e /home/user/.gitconfig ]]; then
  git config --global init.templatedir ""
  git config --global user.name "John Doe"
  git config --global user.email "john.doe@foo.com"
fi
