#!/bin/bash
# Copyright (c) 2014 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is for bash on NaCl. Note that you cannot use external commands
# until the installation is completed. Also, you cannot use features
# which nacl_io does not support yet (e.g., pipes and sub-shells).

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# PACKAGE_LIB_DIR is still used by the devenv tests
# TODO(sbc): remove this and move it into devenv test code somehow
if [[ ${NACL_ARCH} == x86_64 ]]; then
  PACKAGE_LIB_DIR=lib64
else
  PACKAGE_LIB_DIR=lib32
fi

LD_LIBRARY_PATH=/lib:/usr/lib:/usr/${NACL_ARCH}-nacl/usr/lib
LD_LIBRARY_PATH+=:/mnt/http/_platform_specific/${NACL_ARCH}
LIBRARY_PATH=${LD_LIBRARY_PATH}
PATH+=:/mnt/http

# Allow cross development by exporting alternate library paths.
LIBRARY_PATH32=/usr/x86_64-nacl/lib32
LIBRARY_PATH32+=:/usr/i686-nacl/usr/lib
LIBRARY_PATH64=/usr/x86_64-nacl/lib
LIBRARY_PATH64+=:/usr/x86_64-nacl/usr/lib

export RUBYLIB=/usr/lib/ruby/2.0.0
export RUBYLIB=${RUBYLIB}:${RUBYLIB}/${NACL_ARCH}-nacl

# Allow ctrl-c to work.
export ENABLE_CONTROL_C=1

# TODO(bradnelson): Remove when we can install in a more normal location.
# Usually this is in /etc/ssl/certs/, but we don't mount persistent storage
# there yet.
# Point git and curl at root certificates inside the curl package.
export GIT_SSL_CAINFO=/usr/share/curl/ca-bundle.crt
export CURL_CA_BUNDLE=/usr/share/curl/ca-bundle.crt

export TOOLCHAIN=@TOOLCHAIN@
export NACL_DEVENV=1
export LIBRARY_PATH32
export LIBRARY_PATH64
export LD_LIBRARY_PATH
export LIBRARY_PATH
export PATH

if [[ -n $INSTALL_BASE_PACKAGES ]]; then
  marker=/var/lib/devenv_setup_complete
  if [[ ! -e $marker ]]; then
    echo "Performing initial devenv setup"
    if /mnt/http/install-base-packages.sh; then
      mkdir -p /var/lib
      touch $marker
    else
      echo "*** devenv setup failed ***"
    fi
  fi
fi

cd ${HOME}

if [[ -f ~/.bashrc ]]; then
  . ~/.bashrc
fi
