top_srcdir   = /home/jp/lind_project/test_cases/httpd
top_builddir = /home/jp/lind_project/test_cases/httpd
srcdir       = /home/jp/lind_project/test_cases/httpd/server/mpm/event
builddir     = /home/jp/lind_project/test_cases/httpd/server/mpm/event
VPATH        = /home/jp/lind_project/test_cases/httpd/server/mpm/event
include $(top_srcdir)/build/special.mk
