#!/bin/bash

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
	if [[ -f ./configure ]]; then
		./configure --help
		exit 1
	fi
	./buildconf --help
	exit 1
fi

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g3 -fPIC -D__ILP32__'
export CXXFLAGS='-g3 -fPIC -D__ILP32__'
export LDFLAGS='-g3 -fPIC -D__ILP32__'
export PREFIX="${PREFIX:-$HOME/lind_project/lind/repy/repy}"
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

./buildconf
./configure \
	--prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}" \
	--disable-all \
	--enable-opcache=no \
	--disable-zend-signals \
	--disable-inline-optimization \
	--host=x86_64-nacl \
	--with-pic \
	"$@"
make install
