top_srcdir   = /home/jp/lind_project/test_cases/httpd-2.4.37
top_builddir = /home/jp/lind_project/test_cases/httpd-2.4.37
srcdir       = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/arch/unix
builddir     = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/arch/unix
VPATH        = /home/jp/lind_project/test_cases/httpd-2.4.37/modules/arch/unix

include $(top_srcdir)/build/special.mk

