#!/bin/bash
#
# try to ease the burden of building lind (repy, nacl, and glibc toolchain)
#
# Created by Chris Matthews <cmatthew@cs.uvic.ca>
# Updated by Joey Pabalinas <joeypabalinas@gmail.com>

# version and usage strings
cd ..
readonly version=1.0.0-rc4
usage+=$'\n'"Lind $version NaCl Toolchain Build Script"$'\n'
usage+=$'\n'
usage+=$'Usage:\n'
usage+=$'\t'"$0 [-ehv] [targets]"$'\n'
usage+=$'\n'
usage+=$'Options:\n'
usage+=$'\t-e\tUse custom environment instead of defaults for directory paths.\n'
usage+=$'\t-h\tDisplay this help.\n'
usage+=$'\t-q\tSilent build (only errors are printed).\n'
usage+=$'\t-v\tDisplay script version.\n'

# track line number and arguments of current function
args="$*"
line="$LINENO"
# set to zero until we actually start building
start_time=0
# signals which trigger abort() function
err_signals=(ERR INT)
# use the default environment by default
default_env=1

# guard against incompatible compiler flags
unset CFLAGS CPATH CPPFLAGS CXXFLAGS LDFLAGS

# wrapper for desired logging command
#
function print() {
	printf '%s\n' "$@"
}

# calculate total build time
#
function get_build_time() {
	if ((start_time)); then
		end_time="$(date +%s)"
		diff_time="$((end_time - start_time))"
		print $'\a' "It took $diff_time seconds"
	fi
	print "" "All done." >&2
}

# print out error information and abort
#
function abort() {
	local func
	func="${FUNCNAME[1]}"
	print "" "[$0:$line] Error: [function: $func()] [arguments: ${args:-(nil)}]." "" >&2
	exit 1
}

# save stdout
exec 9>&1

# cleanup traps
trap -- '{ exec >&9; get_build_time; }' EXIT
trap -- '{ exec >&9; args="$*" line="$LINENO" abort; }' "${err_signals[@]}"

# option handling
while getopts :eqhv opt; do
	case "$opt" in
	# use custom environment
	e)
		default_env=0;;

	# only print errors
	q)
		exec >/dev/null;;

	# show usage information
	h)
		print "$usage" >&2
		exit;;

	# show version information
	v)
		print "Lind $version NaCl Toolchain Build Script" >&2
		exit;;

	# otherwise exit after printing the bad option and usage
	:|?)
		print "Illegal option letter: '$OPTARG'" "$usage" >&2
		false;;
	esac
done
shift "$((OPTIND - 1))"

if ((default_env)); then
	export LIND_PREFIX="${LIND_PREFIX:-$HOME}"
	export LIND_BASE="${LIND_BASE:-$LIND_PREFIX/lind_project}"
	export LIND_SRC="${LIND_SRC:-$LIND_BASE/lind}"
	export REPY_PATH="${REPY_PATH:-$LIND_SRC/repy}"
	export NACL_SDK_ROOT="${NACL_SDK_ROOT:-$REPY_PATH/sdk}"
	export PYTHON="${PYTHON:-python2}"
	export PNACLPYTHON="${PNACLPYTHON:-python2}"
	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-/lib/glibc}"
	export PATH="${PATH}:-$LIND_PREFIX/lind_project/src/scripts"

	print
	print '======================================================'
	print 'USING DEFAULT LIND ENVIRONMENT:'
	print '======================================================'
	print
	cat <<-EOF
		export LIND_PREFIX="$LIND_PREFIX"
		export LIND_BASE="$LIND_BASE"
		export LIND_SRC="$LIND_SRC"
		export REPY_PATH="$REPY_PATH"
		export NACL_SDK_ROOT="$NACL_SDK_ROOT"
		export PYTHON="$PYTHON"
		export PNACLPYTHON="$PNACLPYTHON"
		export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
		export PATH="$PATH"
	EOF
	print
	print '======================================================'
	print
fi

if [[ -z "$REPY_PATH" ]]; then
	print "Need to set REPY_PATH" >&2
	false
fi
if [[ -z "$LIND_BASE" ]]; then
	print "Need to set LIND_BASE" >&2
	false
fi
if [[ -z "$LIND_SRC" ]]; then
	print "Need to set LIND_SRC" >&2
	false
fi

if command -v nproc >/dev/null 2>&1; then
	NPROC="$(($(nproc) + 2))"
else
	NPROC=6
fi
readonly JOBS="${JOBS:-$NPROC}"
readonly OS_NAME="$(uname -s)"
if [[ "$OS_NAME" == Darwin ]]; then
	readonly OS_SUBDIR="mac"
elif [[ "$OS_NAME" == Linux ]]; then
	readonly OS_SUBDIR="linux"
else
	readonly OS_SUBDIR="win"
fi
readonly MODE="dbg-$OS_SUBDIR"
readonly LIND_BASE="$LIND_BASE"
readonly LIND_SRC="$LIND_SRC"
readonly EXPERIMENTS_DIR="$LIND_BASE/lind_experiments"
readonly MISC_DIR="$LIND_BASE/src/scripts"
readonly NACL_SRC="$LIND_SRC/nacl_src"
readonly NACL_BASE="$NACL_SRC/native_client"
readonly NACL_TOOLCHAIN_BASE="$NACL_BASE/tools"
readonly LIND_GLIBC_SRC="$LIND_BASE/src/lind_glibc"
readonly NACL_GCC_SRC="$LIND_BASE/src/nacl-gcc"
readonly NACL_BINUTILS_SRC="$LIND_BASE/src/nacl-binutils"
readonly NACL_REPY="$LIND_BASE/src/nacl_repy"

readonly REPY_PATH="$REPY_PATH"
readonly REPY_PATH_BIN="$REPY_PATH/bin"
readonly REPY_PATH_REPY="$REPY_PATH/repy"
readonly REPY_PATH_LIB="$REPY_PATH/lib"
readonly REPY_PATH_SDK="$REPY_PATH/sdk"
readonly NACL_SDK_ROOT="$REPY_PATH_SDK"

readonly LIND_URL='https://github.com/Lind-Project/lind_project.git'
readonly LIND_EXPERIMENTS_URL='https://github.com/Lind-Project/lind_experiments.git'
readonly LIND_MISC_URL='https://github.com/Lind-Project/Lind-misc.git'
readonly LSS_URL='https://github.com/Lind-Project/linux-syscall-support.git'
readonly NACL_REPY_URL='https://github.com/Lind-Project/nacl_repy.git'
readonly NACL_GCC_URL='https://github.com/Lind-Project/nacl-gcc.git'
readonly NACL_BINUTILS_URL='https://github.com/Lind-Project/nacl-binutils.git'
readonly NATIVE_CLIENT_URL='https://github.com/Lind-Project/native_client.git'
readonly LIND_GLIBC_URL='https://github.com/Lind-Project/Lind-GlibC.git'

readonly -a PYGREPL=(grep '-RPIl' -- '(^|[\s'"'"'"/-])(python)(\s|\.exe|\b)' './')
readonly -a PYGREPV=(grep '-Pv' -- '\.(git|.?html|cc?|h|exp|so\.old|so)\b')
readonly -a PYSED=(sed '-r' 's_(^|[\s'"'"'"/-])(python)(\.exe|\b)_\1\22\3_g')
readonly -a PNACLGREPL=(grep '-RIFwl' -- 'PNACLPYTHON' './')
readonly -a PNACLGREPV=(grep '-Pv' -- '\.(git|.?html|cc?|h|exp|so\.old|so)\b')
readonly -a PNACLSED=(sed -r 's_$\{?PNACLPYTHON\}?_python2_g')
readonly -a RSYNC=(rsync '--progress=status2,stats2' '-ahhkpvA')

# clean downloaded sources
#
function clean_src() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	print "Cleaning Lind..."
	cd "$LIND_BASE"
	rm -rf -- lind_experiments lind-misc lss
	rm -rf -- nacl_repy nacl-gcc nacl-binutils lind_glibc
}

# download sources
#
function download_src() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	local pip_bin pip_ver nacl_rev
	local -A git_deps toolchain_deps

	# populate associative arrays
	git_deps[lind_experiments]="$LIND_EXPERIMENTS_URL"
	git_deps[lind-misc]="$LIND_MISC_URL"
	git_deps[lss]="$LSS_URL"
	git_deps[nacl_repy]="$NACL_REPY_URL"
	git_deps[nacl-gcc]="$NACL_GCC_URL"
	git_deps[nacl-binutils]="$NACL_BINUTILS_URL"
	git_deps[lind_glibc]="$LIND_GLIBC_URL"
	git_deps[native_client]="$NATIVE_CLIENT_URL"
	toolchain_deps[gcc]="$NACL_GCC_SRC"
	toolchain_deps[glibc]="$LIND_GLIBC_SRC"
	toolchain_deps[binutils]="$NACL_BINUTILS_SRC"

	# clone and symlink dependencies
	mkdir -p "$LIND_BASE" "$LIND_SRC" "$NACL_SRC"
	cd "$LIND_BASE"

	# make sure we are in the git root of "Lind-Project/lind_project"
	git init
	if [[ "$(git config remote.origin.url)" != *Lind-Project/lind_project* ]]; then
		if ! git remote add origin "$LIND_URL"; then
			print "LIND_BASE already an initialized git directory" >&2
			false
		fi
		git fetch --all
		#git checkout master
	fi

	# symlink submodules
	git submodule update --init --recursive --remote .
	# iterate through all subdirectories, fetch from remote, restructure lind directory, and checkout to develop
	for dir in "${!git_deps[@]}"; do
		[[ ! -e "src/$dir" ]] && git clone "${git_deps[$dir]}" "src/$dir"
		rm -rf -- "${LIND_SRC:?}/$dir"
		ln -Trsfv "$LIND_BASE/src/$dir" "$LIND_SRC/$dir"
		(cd "$LIND_SRC/$dir" && git checkout develop)
        done

	# initialize native client toolchain
	ln -Trsfv "$LIND_BASE/src/native_client" "$NACL_BASE"
	cd "$LIND_BASE/src"
	# default to develop branch if not building inside travis
	nacl_rev="${NATIVE_CLIENT_URL}@${BRANCH:-develop}"
	gclient config --name=native_client --git-deps "$nacl_rev"
	gclient sync

	# symlink toolchain dependencies
	cd "$NACL_TOOLCHAIN_BASE"
	rm -rf -- SRC
	make sync-pinned
	for dir in "${!toolchain_deps[@]}"; do
		rm -rf -- "SRC/$dir"
		ln -Trsfv "${toolchain_deps[$dir]}" "SRC/$dir"
		(cd "SRC/$dir")
	done

	# gclient overwrites our Docker Makefile
	cd "$LIND_BASE"
	git checkout -- Makefile
	rm -rfv -- _gclient_* _bad_scm
}

# wipe the entire modular build toolchain build tree, then rebuild it
# warning: this can take a while!
#
function clean_toolchain() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	cd "$NACL_TOOLCHAIN_BASE" && rm -rf out BUILD
}

# copy the toolchain into the repy subdir
#
function install_to_path() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	print "** Sending NaCl files to $REPY_PATH **"

	mkdir -p "$REPY_PATH_BIN"
	mkdir -p "$REPY_PATH_LIB/glibc"
	mkdir -p "$REPY_PATH_SDK/toolchain/${OS_SUBDIR}_x86_glibc"
	mkdir -p "$REPY_PATH_SDK/tools"

	"${RSYNC[@]}" "$NACL_TOOLCHAIN_BASE/out/nacl-sdk/" "$REPY_PATH_SDK/toolchain/${OS_SUBDIR}_x86_glibc"

	"${RSYNC[@]}" "$NACL_BASE/scons-out/${MODE}-x86-64/staging/" "$REPY_PATH_BIN"

	#install scripts
	cp -pfv "$MISC_DIR/lind" "$REPY_PATH_BIN/lind"
	cp -pfv "$MISC_DIR/lindfs" "$REPY_PATH_BIN/lindfs"
	chmod +x "$REPY_PATH_BIN/lind" "$REPY_PATH_BIN/lindfs"

	"${RSYNC[@]}" "$NACL_TOOLCHAIN_BASE/out/nacl-sdk/x86_64-nacl/lib/"  "$REPY_PATH_LIB/glibc"

	print "Copying glibc into repy virtual filesytem"
	cd "$REPY_PATH/repy"
	"$REPY_PATH_BIN/lindfs" cp "$REPY_PATH_LIB/"

	print "Done."
}

# install repy into $REPY_PATH with the prepare_tests script.
#
function build_repy() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	set -o errexit

	local short_ver lind_serv

	mkdir -pv "$REPY_PATH_REPY"
	print "Building Repy in $REPY_SRC to $REPY_PATH"

	# checkout the correct revision if building inside travis
	cd "$NACL_REPY"
	if [[ -n "$BRANCH" ]]; then
		git fetch --all
		# TODO: make branch names consistent across our repositories and
		# avoid the need for the `|| true` here
		#
		# Some branches such as the lind branch in native_client don't have
		# matching branches in the other submodules and the checkout fails
		# if you tried to checkout, say, the lind branch of nacl_repy
		#
		# -jp
		git checkout "$BRANCH" || true
	fi
	cp -fv ./seattlelib/xmlrpc* "$REPY_PATH_REPY/"
	python2 ./preparetest.py -t -f "$REPY_PATH_REPY"
	print "Done building Repy in \"$REPY_PATH_REPY\""
	cd seattlelib

	# strip the patch version for repy
	short_ver="${version%.*-*}${version/*-/-}"
	lind_serv=lind_server.mix
	sed '/VERSION/ s/\$[^\$]*\$/\$'"$short_ver"'\$/' \
		<"./$lind_serv" \
		>"./$lind_serv.new"
	cat \
		<"./$lind_serv.new" \
		>"./$lind_serv"
	rm -fv -- -- "./$lind_serv.new"
	for file in *.mix; do
		"$MISC_DIR/check_includes.sh" "$file"
	done

	set +o errexit
}

# run applications test suites.
#
function test_apps() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	set +o errexit

	cd "~/lind/tests" && ./test.sh
}

# run glibc test suites.
#
function test_glibc() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	set -o errexit

	cd "$MISC_DIR/glibc_test"
	make clean
	PATH="$LIND_BASE:$PATH" make all
	cd ..
	rm -rfv -- lind.metadata linddata.*
	lind "$MISC_DIR/glibc_test/glibc_tester.nexe"
}

# run repy test suites.
#
function test_repy() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	# some of our unit tests fail
	set +o errexit
	cd "$REPY_PATH/repy"

	# ignore these signals during testing
	trap -- '' ERR TERM
	for file in ut_lind_*; do
		print "$file"
		python2 "$file"
	done
	# reset signal dispositions
	trap -- - ERR TERM

	# run the struct test
	file="ut_seattlelibtests_teststruct.py"
	print "$file"
	python2 "$file"
}

# run system call test suites.
#
function test_syscalls() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	local cc_cmd

	cd "$LIND_BASE/test_cases"
	cc_cmd="$REPY_PATH_SDK/toolchain/linux_x86_glibc/bin/x86_64-nacl-gcc"

	# ignore these signals during testing
	trap '' ERR TERM
	for file in *.c; do
		print "" "** Testing $file **" ""
		"$cc_cmd" "$file" -o "$REPY_PATH/repy/${file%%.c}"
		"$REPY_PATH_BIN/lindfs" update "$REPY_PATH/repy/${file%%.c}"
		"$REPY_PATH_BIN/lind" "/${file%%.c}"
	done
	print ""
	# reset signal dispositions
	trap - ERR INT TERM
}

# update, build and test everything. if there is a problem, freak out.
#
function nightly_build() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	clean_nacl
	clean_src
	clean_toolchain

	download_src
	build_nacl
	build_repy
	build_glibc
	install_to_path

	build_docker

	# test_apps
	# test_glibc
	# test_repy
	test_syscalls
}

# run the nacl build.
#
function build_nacl() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	print "Building NaCl"

	# the pnacl script doesn't respect PYTHON or PNACLPYTHON
	cd "$NACL_BASE/toolchain/pnacl_linux_x86/newlib/bin"
	"${PYGREPL[@]}" 2>/dev/null \
		| "${PYGREPV[@]}" \
		| while read -r file; do
			# preserve executability
			"${PYSED[@]}" <"$file" >"$file.new"
			cat <"$file.new" >"$file"
			rm -f -- "$file.new"
		done

	# checkout the correct revision if building inside travis
	cd "$NACL_BASE"
	if [[ -n "$BRANCH" ]]; then
		git fetch --all
		# TODO: make branch names consistent across our repositories and
		# avoid the need for the `|| true` here
		#
		# Some branches such as the lind branch in native_client don't have
		# matching branches in the other submodules and the checkout fails
		# if you tried to checkout, say, the lind branch of nacl_repy
		#
		# -jp
		git checkout "$BRANCH" || true
	fi
	# skip broken tests for now
	PATH="$LIND_BASE:$PATH" \
		python2 ./scons.py \
			--verbose \
			--mode="$MODE,nacl" \
			--nacl_glibc \
			-j"$JOBS" \
			nacl_pic=1 \
			werror=0 \
			skip_trusted_tests=1 \
			disable_flaky_tests=1 \
			platform=x86-64
	print "Done building NaCl"
}

# run clean on nacl build.
#
function clean_nacl() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	cd "$NACL_BASE"
	PATH="$LIND_BASE:$PATH" \
		python2 ./scons.py \
			--verbose \
			--mode="$MODE,nacl" \
			--nacl_glibc \
			-j"$JOBS" \
			-c \
			nacl_pic=1 \
			werror=0 \
			platform=x86-64
	print "Done Cleaning NaCl"
}

# build glibc from source
#
function build_glibc() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	# the build is long and borning, so execute this first if it exists
	print ""
	fortune 2>/dev/null || print "Fortune Not Found. Skipping." >&2
	print "" "Copying component.h header to glibc: "

	print "Building glibc"

	# checkout the correct revision if building inside travis
	cd "$NACL_BASE"
	if [[ -n "$BRANCH" ]]; then
		git fetch --all
		# TODO: make branch names consistent across our repositories and
		# avoid the need for the `|| true` here
		#
		# Some branches such as the lind branch in native_client don't have
		# matching branches in the other submodules and the checkout fails
		# if you tried to checkout, say, the lind branch of nacl_repy
		#
		# -jp
		git checkout "$BRANCH" || true
	fi
	# turns out this works better if you do it from the nacl base dir
	cd "$NACL_TOOLCHAIN_BASE"
	rm -rf -- BUILD out
	make clean
	PATH="$LIND_BASE:$PATH" make -j"$JOBS" build-with-glibc

	print "Done building toolchain"
}

# perform an incremental glibc build
#
function update_glibc() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	cd "$NACL_TOOLCHAIN_BASE"
	PATH="$LIND_BASE:$PATH" make -j"$JOBS" updateglibc
}

# perform a clean glibc build
#
function update_glibc2() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	cd "$NACL_TOOLCHAIN_BASE"
	rm -rf -- BUILD/stamp-glibc64
	PATH="$LIND_BASE:$PATH" make -j"$JOBS" BUILD/stamp-glibc64
}

# build docker images
#
function build_docker() {
	trap -- 'args="$*" line="$LINENO" abort' "${err_signals[@]}"

	cd "$LIND_BASE"
	docker image rm -f alyptik/lind:base alyptik/lind:prebuiltsdk alyptik/lind:latest
	docker build -t alyptik/lind:base ./docker/base
	docker build -t alyptik/lind:prebuiltsdk ./docker/prebuiltsdk
	docker build -t alyptik/lind:naclruntime ./docker/naclruntime
	docker build --cache-from=alyptik/lind:naclruntime -t alyptik/lind:latest ./docker/naclruntime
}

# prompt for target if none given on command line
PS3=$'\n'"Build which target? "
list=(all download repy nacl glibc install)
list+=(cleanall cleannacl cleansources cleantoolchain)
list+=(updateglibc updateglibc2 docker nightly testall)
list+=(testapps testglibc testrepy testsyscalls)
if ((!$#)); then
	select choice in "${list[@]}"; do
		set -- "$choice"
		break
	done
fi

# all scripts assume we start here
start_time="$(date +%s)"

# start virtualenv if needed
if [[ -z "$VIRTUAL_ENV" ]]; then
	# find pip executable
	if command -v pip2 >/dev/null 2>&1; then
		pip_bin="pip2"
	elif command -v pip >/dev/null 2>&1; then
		pip_bin="pip"
	else
		print "Need to install pip/pip2 in order to build Lind" >&2
		false
	fi
	# check pip version
	pip_ver="$("$pip_bin" --version | sed 's/.*(python \([0-9\.]\+\)).*/\1/')"
	if [[ "$pip_ver" != 2* ]]; then
		print "Need python2 version of pip in order to build Lind" >&2
		false
	fi
	# install virtualenv modules
	if ! "$pip_bin" install -U --user virtualenv; then
		print "Need python virtualenv/virtualenv2 in order to build Lind" >&2
		false
	fi

	# start up virtualenv
	if ! python2 -m virtualenv "$LIND_BASE/venv"; then
		print "Command \`python2 -m virtualenv ./venv\` failed" >&2
		false
	fi
	# shellcheck disable=SC1090
	. "$LIND_BASE/venv/bin/activate"
	# install pip dependencies
	if ! pip install -Ur "$LIND_BASE/requirements.txt"; then
		print "Installing dependencies from requirements.txt failed" >&2
		false
	fi
fi

# show command that will be executed
print "" "Command line arguments: $0 $*" ""

for word in "$@"; do
	case "$word" in
	download)
		download_src;;
	repy)
		build_repy;;
	nacl)
		build_nacl;;
	glibc)
		build_glibc;;
	all)
		build_nacl
		build_repy
		build_glibc
		install_to_path;;
	install)
		install_to_path;;
	cleanall)
		clean_nacl
		clean_src
		clean_toolchain;;
	cleannacl)
		clean_nacl;;
	cleansources)
		clean_src;;
	cleantoolchain)
		clean_toolchain;;
	updateglibc)
		update_glibc;;
	updateglibc2)
		update_glibc2;;
	docker)
		print "Building docker images"
		build_docker;;
	nightly)
		print "Nightly build"
		nightly_build;;
	testall)
		print "Testing all"
		test_apps
		test_glibc
		test_repy
		test_syscalls;;
	testapps)
		print "Testing applications"
		test_apps;;
	testglibc)
		print "Testing glibc"
		test_glibc;;
	testrepy)
		print "Testing repy"
		test_repy;;
	testsyscalls)
		print "Testing syscalls"
		test_syscalls;;
	*)
		print "Error: Did not find a build target for that number. Exiting..." >&2
		abort;;
	esac
done
