.TH "chcon" 1 "GNU coreutils 8.30.10-e5dae2-dirty" "User Commands"
.SH NAME
chcon \- a GNU coreutils 8.30.10-e5dae2-dirty program
.SH DESCRIPTION
.B OOPS!
We were unable to create a proper manual page for
.B chcon.
For concise option descriptions, run
.IP
.B env chcon --help
.PP
The full documentation for
.B chcon
is maintained as a Texinfo manual, which should be accessible
on your system via the command
.IP
.B info \(aq(coreutils) chcon invocation\(aq
