#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --build-cc
		    --install-cxx
		    --cxxflags
		    --cxxpchflags
		    --cxxldflags
EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/home/lind/lind_project/tests/applications/build-gcc/x86_64-unknown-linux-gnu/32/libstdc++-v3
SRC_DIR=/home/lind/lind_project/tests/applications/gcc-4.4.3/libstdc++-v3
PREFIX_DIR=/usr/local/gcc-4.4.3/
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I/home/lind/lind_project/tests/applications/build-gcc/x86_64-unknown-linux-gnu/32/libstdc++-v3/include/x86_64-unknown-linux-gnu -I/home/lind/lind_project/tests/applications/build-gcc/x86_64-unknown-linux-gnu/32/libstdc++-v3/include -I/home/lind/lind_project/tests/applications/gcc-4.4.3/libstdc++-v3/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build="/home/lind/lind_project/tests/applications/build-gcc/./gcc/xgcc -shared-libgcc -B/home/lind/lind_project/tests/applications/build-gcc/./gcc -nostdinc++ -L/home/lind/lind_project/tests/applications/build-gcc/x86_64-unknown-linux-gnu/32/libstdc++-v3/src -L/home/lind/lind_project/tests/applications/build-gcc/x86_64-unknown-linux-gnu/32/libstdc++-v3/src/.libs -B/usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/bin/ -B/usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/lib/ -isystem /usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/include -isystem /usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/sys-include  -m32"
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/g++ ,'`
      echo ${CXX}
      ;;
    --build-cc)
      CC_build="/home/lind/lind_project/tests/applications/build-gcc/./gcc/xgcc -B/home/lind/lind_project/tests/applications/build-gcc/./gcc/ -B/usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/bin/ -B/usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/lib/ -isystem /usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/include -isystem /usr/local/gcc-4.4.3//x86_64-unknown-linux-gnu/sys-include  -m32"
      CC="$CC_build"
      echo ${CC}
      ;;
    --cxxflags)
      CXXFLAGS_default="-g -O2 -D_GLIBCXX_ASSERT -fmessage-length=0"
      CXXFLAGS_config="-ffunction-sections -fdata-sections -fgnu89-inline -g -O2 -D_GNU_SOURCE  "
      echo ${CXXFLAGS_default} ${CXXFLAGS_config}
      ;;
    --cxxparallelflags)
      CXXFLAGS_parallel="-D_GLIBCXX_PARALLEL -fopenmp
			 -B${BUILD_DIR}/../libgomp 
                         -I${BUILD_DIR}/../libgomp 
			 -L${BUILD_DIR}/../libgomp/.libs -lgomp"
      echo ${CXXFLAGS_parallel}
      ;;
    --cxxpchflags)
      PCHFLAGS=""
      echo ${PCHFLAGS}
      ;;
    --cxxldflags)
      SECTIONLDFLAGS="-Wl,--gc-sections  "
      echo ${SECTIONLDFLAGS}
      ;;
    *)
      print_usage
      ;;
esac

exit 0
