#!/bin/bash

export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LD=x86_64-nacl-ld
export CFLAGS='-g -fno-pie -O3'
export CXXFLAGS='-g -fno-pie -O3'
export LDFLAGS='-g -fno-pie -O3'
export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"


make makefile-nacl build
